// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for SetZerotierNetworkStatusJSONBodyStatus.
const (
	Offline SetZerotierNetworkStatusJSONBodyStatus = "offline"
	Online  SetZerotierNetworkStatusJSONBodyStatus = "online"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// HealthPorts defines model for HealthPorts.
type HealthPorts struct {
	TCP *[]int `json:"tcp,omitempty"`
	UDP *[]int `json:"udp,omitempty"`
}

// HealthServices defines model for HealthServices.
type HealthServices struct {
	NotRunning *[]string `json:"not_running,omitempty"`
	Running    *[]string `json:"running,omitempty"`
}

// ZTInfo defines model for ZTInfo.
type ZTInfo struct {
	Id     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// GetHealthPortsOK defines model for GetHealthPortsOK.
type GetHealthPortsOK struct {
	Data *HealthPorts `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetHealthServicesOK defines model for GetHealthServicesOK.
type GetHealthServicesOK struct {
	Data *HealthServices `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetZTInfoOK defines model for GetZTInfoOK.
type GetZTInfoOK = ZTInfo

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// UpdateLocalStorageDisplayNameJSONBody defines parameters for UpdateLocalStorageDisplayName.
type UpdateLocalStorageDisplayNameJSONBody struct {
	DisplayName *string `json:"display_name,omitempty"`
	MountPoint  *string `json:"mount_point,omitempty"`
}

// SetZerotierNetworkStatusJSONBody defines parameters for SetZerotierNetworkStatus.
type SetZerotierNetworkStatusJSONBody struct {
	Status *SetZerotierNetworkStatusJSONBodyStatus `json:"status,omitempty"`
}

// SetZerotierNetworkStatusJSONBodyStatus defines parameters for SetZerotierNetworkStatus.
type SetZerotierNetworkStatusJSONBodyStatus string

// UpdateLocalStorageDisplayNameJSONRequestBody defines body for UpdateLocalStorageDisplayName for application/json ContentType.
type UpdateLocalStorageDisplayNameJSONRequestBody UpdateLocalStorageDisplayNameJSONBody

// SetZerotierNetworkStatusJSONRequestBody defines body for SetZerotierNetworkStatus for application/json ContentType.
type SetZerotierNetworkStatusJSONRequestBody SetZerotierNetworkStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Test file methods
	// (GET /file/test)
	GetFileTest(ctx echo.Context) error
	// Get log
	// (GET /health/logs)
	GetHealthlogs(ctx echo.Context) error
	// Get port in use
	// (GET /health/ports)
	GetHealthPorts(ctx echo.Context) error
	// Get service status
	// (GET /health/services)
	GetHealthServices(ctx echo.Context) error
	// Update display name for one mount point
	// (PUT /local_storage/display_name)
	UpdateLocalStorageDisplayName(ctx echo.Context) error
	// Get display names for all managed mount points
	// (GET /local_storage/display_names)
	GetLocalStorageDisplayNames(ctx echo.Context) error
	// Get Zerotier info
	// (GET /zt/info)
	GetZerotierInfo(ctx echo.Context) error
	// Set Zerotier network status
	// (PUT /zt/{network_id}/status)
	SetZerotierNetworkStatus(ctx echo.Context, networkId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFileTest converts echo context to params.
func (w *ServerInterfaceWrapper) GetFileTest(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFileTest(ctx)
	return err
}

// GetHealthlogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthlogs(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthlogs(ctx)
	return err
}

// GetHealthPorts converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthPorts(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthPorts(ctx)
	return err
}

// GetHealthServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthServices(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthServices(ctx)
	return err
}

// UpdateLocalStorageDisplayName converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateLocalStorageDisplayName(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateLocalStorageDisplayName(ctx)
	return err
}

// GetLocalStorageDisplayNames converts echo context to params.
func (w *ServerInterfaceWrapper) GetLocalStorageDisplayNames(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetLocalStorageDisplayNames(ctx)
	return err
}

// GetZerotierInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetZerotierInfo(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetZerotierInfo(ctx)
	return err
}

// SetZerotierNetworkStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetZerotierNetworkStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "network_id" -------------
	var networkId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "network_id", runtime.ParamLocationPath, ctx.Param("network_id"), &networkId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter network_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetZerotierNetworkStatus(ctx, networkId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/file/test", wrapper.GetFileTest)
	router.GET(baseURL+"/health/logs", wrapper.GetHealthlogs)
	router.GET(baseURL+"/health/ports", wrapper.GetHealthPorts)
	router.GET(baseURL+"/health/services", wrapper.GetHealthServices)
	router.PUT(baseURL+"/local_storage/display_name", wrapper.UpdateLocalStorageDisplayName)
	router.GET(baseURL+"/local_storage/display_names", wrapper.GetLocalStorageDisplayNames)
	router.GET(baseURL+"/zt/info", wrapper.GetZerotierInfo)
	router.PUT(baseURL+"/zt/:network_id/status", wrapper.SetZerotierNetworkStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYTXPbNhD9Kxi0h6QjiardtK5mcnDqxvGksT2Vc4nlUWByRSImAXZ3aVvx6L93AFAS",
	"JdFfqd3JSRI+dt8+YBdvdSNjW5TWgGGSgxuJQKU1BP7HPvA7UDlnxxaZjt67sdgaBsPuqyrLXMeKtTXR",
	"F7LGjVGcQaH8bJ4fTeTg9Eb+iDCRA/lDtHQVhXUUvVEEf9c+5axzI0u0JSDrgCBR7I3dZaIBUc5ms7PZ",
	"bNaRCVCMunTY5EAevZezzjKcIeCljuE7j2iO8t6gPp0cmIl9ZDB3+Q8G5a0+5+EdGAY0KndIAf9EtPhk",
	"GFZp3EQy9y2CcxG8N8A9IR/3YXGszDq1MX/KKzsG63egACKV+olVQ/WEQOAKDSTifCooxEc6AaEngjNA",
	"EJqEMlPZkXCtijIHOZCyIxFUcmTyqRwwVtCRPC3dDDFqkwbgzWTZwMVx6T40Q+F/L4zv9BfGtGFIwTNd",
	"jyhE5aBcd1PbNapwYyd/HLsVVXKLwVfbjzT4ce+4GcAiNzZiMJbHWBnjIm51LY0urKUeBRNyg6Y1HLOO",
	"fIi9bqoYrtT04XZdNHWmbUShk1UfP29t//Lq1992fu+32Q0cNdcf6sIeDdvWEiuu1iKwJtemBbGHSBBX",
	"qHk6dLc7oFNxDERjthfgs0i7u5uBSgDlHI3crTizqL/6hFvaVqV+D3X0uo59NQlGVb+/HZc65grB/4CR",
	"EUKIMEG2whhEAYlWr0fyRYkwAaRubHOLXZ+DMBCJwouXIykIYwJ+PZIZc0mDKEJ11Us1Z9V5RYB1eejF",
	"togcZycQZ1FuUxsVSpsoHG39MT5XxgCOnemx0WnG451+v7zulSYdyW8FmjtDz4SUr7Q3Pz7PK7gbrC5S",
	"oXLnPlydAOj/RROQRGsnPzIBkdg9PhAl2kudAIlCUwx5rgzYikQBnNmExMSiSPRkAgiGBcVgFGpLPWfl",
	"rUWhiSpwpTMRiaa4ItLWUEeUOSgCcalJs6uw4nRf87vqXCCUljRbnJ69mDMRWFgNPUB8KSyKL1YbcWor",
	"FHuaYovJcmcSBvxWbS41Q7RzOOT9D1fwKXvZG/k00dzIYBe07MhLQArJcbnlktiWYFSp5UBu9/q9bdmR",
	"peLM52Y00TlEDOTfvBR4M8FOgFi4ZXPeetKbRJ+qB4kcOFXxVufgVvp3pSEKt/r9297Lxbqo8QjPOvLV",
	"Y7a0iQpfh6qiUDhtw+9oUynJwal82xw+c/uizL8Y7nZSg5KNeMPD4le1R3yLlLAxA3eJEVSxKikmFgvF",
	"ciDPtXHIWx/kNn31xHztA4vcpg2WQqztPJVzbXA3UUFCfMvd2OgqnidiF4fQRlQED4ycGqKiNXGc2VoL",
	"iPCOCjsRoOJMfK5VwE+fRW2mNanW1Mt/oq/RxTwPg3Ugdaj3kZjbWOVjYosqBVfqylxNx3NpUlYtl+lj",
	"mSiGv9zGYdi3F7Ydul2OnH8qIH5jk+mjtPxax7UGZV0ldd/ttQmlwlaGx6XVweNyV7S3e7LbksyLEXv+",
	"BWKu5dN3VjsD5aLmRDhO/KtpDQgfsQgRLw/bH4+oz+fes76zctxy0vT9PTHu+jc5CtJC5bkolFEpJE2y",
	"6B62vnI0V7q3lpVPgJY1oHArW0vHfIVvGL6xcCz+KXgexlaCaJCyGF+tGF85ujHAVxYvxjqZRcvWpK4W",
	"qzQNmx7qfXVt2iRsuCTsMCwdzqtYqVAVwIDk/8tZdTK3qxPZCX2NU1bLrmaJt65PGiGZ99vLCrReG86e",
	"qpg12jdTFY7cRfNmJxP/7azzkNbuqarV896qO878nvvV6Fz9Ma/2rKdn7kjCXyvhGlSYu9p+uVV3LdIt",
	"qB1sCOgMaKEyhUJwIiMRbEWcQXzhO4igKXyrsZQKbqLRzbhJRWRjrRiS+XtLPbG8b2tP7azTgkU0Ra8r",
	"UvZKTG3l8GjHsIpZXGnOvGaedz8IMVvUQMKaJi6aEkPRWyJYUdSOlOsuq3QfbVUGbup1Hza0+IZMOJv9",
	"GwAA//8tO4SVbxYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
